config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#delete", as: :destroy_session

  post "/menu_items/:id/cart" => "cart#add", as: :cart_add_item
  delete "/menu_items/:id/cart" => "cart#remove", as: :cart_remove_item

  get "/invoices" => "invoices#list", as: :invoices_list
  get "/invoices/users/:id" => "invoices#users_list", as: :invoices_users

  resources :cafe
  resources :menu_items
  resources :menu
  resources :order
  resources :users
end

app/models/Invoices.rb
class Invoices
  attr_reader :start_date, :end_date

  def initialize(params)
    params ||= {}
    @start_date = params[:start_date] == nil ? 7.days.ago.to_date : params[:start_date]
    @end_date = params[:end_date] == nil ? Date.today : params[:end_date]
  end

  def range
    Order.where("date BETWEEN ? AND ?", @start_date, @end_date)
  end
end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def list
    start_date = params[:start_date]
    end_date = params[:end_date]
    if start_date == "" || end_date == ""
      flash[:error] = "Please enter valid date in both fields."
      redirect_back(fallback_location: invoices_list_path)
    else
      unless start_date == nil || end_date == nil
        @list = Order.where("date BETWEEN ? AND ?", start_date, end_date).order("id")
      else
        @list = nil
      end
    end
  end

  def users_list
    start_date = params[:start_date]
    end_date = params[:end_date]
    user_id = params[:id]
    @user_name = User.find(user_id).name
    if start_date == "" || end_date == ""
      flash[:error] = "Please enter valid date in both fields."
      redirect_back(fallback_location: invoices_users_path)
    else
      unless start_date == nil || end_date == nil
        @list = Order.where("date BETWEEN ? AND ? AND user_id = ?", start_date, end_date, user_id).order("id")
      else
        @list = nil
      end
    end
  end
end

app/views/invoices/_invoice-list.html.erb
<section class = "DateSection">
  <h2 class = "Invoices-Title"> Date Range: </h2>
  <%= form_with(url: path, method: "get", class: "ListInvoices") do |form|%>

    <p class = "ErrorMessage"> <%= flash[:error] %> </p>
    <section class = "StartDate">
      <p class = "StartDate-Tag"> Start Date: </p>
      <%= date_field_tag "start_date", nil, class: "StartDate-Date" %>
    </section>

    <section class = "EndDate">
      <p class = "EndDate-Tag"> End Date: </p>
      <%= date_field_tag "end_date", nil, class: "EndDate-Date" %>
    </section>

    <%= button_tag "List", class: "ListInvoices-Button", onclick: "this.form.submit()"%>
  <% end %>
</section>

<section class = "InvoicesSection">
  <p class = "InvoiceList-Tag"> List of Invoices: </p>
  <%if list == nil || list == [] %>
    <section class = "Orderpage-Content">
      <p class = "Orderpage-ContentText"> No Invoices in the given range </p>
    </section>
  <% else %>
    <table class = "Orders">

      <tr class = "Order">
        <th class = "Order-Head"> Order Id </th>
        <th class = "Order-Head"> User </th>
        <th class = "Order-Head"> Order Date & Time </th>
        <th class = "Order-Head"> Total Price </th>
        <th class = "Order-Head"> Delivery Status </th>
      </tr>

      <% list.each do |order|%>
        <tr class = "Order">
          <td class = "Order-Id"> <%= order.id %> </td>
          <td class = "User"> <%= User.find(order.user_id).name %> </td>
          <td class = "Order-Timestamp"> <%= order.date.strftime("%B %e, %Y at %I:%M %p") %> </td>
          <td class = "Order-TotalPrice"> Rs. <%= order.total_amount%> /- </td>
          <td class = "Order-DeliveryStatus"> <%= order.delivered_at == nil ? "Yet to be Delivered" : "Delivered" %> </td>
          <td class = "Order-View"> <%= link_to "view", order_path(order.id), class: "OrderView-link" %> </td>
        </tr>
      <% end %>

    </table>
  <% end %>
</section>

app/views/invoices/list.html.erb
<section class = "InvoicesPage">
  <%= render partial: "invoice-list", locals: { list: @list, path: invoices_list_path } %>
</section>

app/views/invoices/users_list.html.erb
<section class = "UserName-Head">
  <h2 class = "UserName-Title"> User name:  </h2>
  <h3 class = "UserName-Name"> <%= @user_name %> </h3>
</section>

<section class = "InvoicesPage">
  <%= render partial: "invoice-list", locals: { list: @list, path: invoices_users_path } %>
</section>