config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/" => "home#index"

  get "/signin" => "sessions#new", as: :new_sessions
  post "/signin" => "sessions#create", as: :sessions
  delete "/signout" => "sessions#delete", as: :destroy_session

  post "/menu_items/:id/cart" => "cart#add", as: :cart_add_item
  delete "/menu_items/:id/cart" => "cart#remove", as: :cart_remove_item

  get "/invoices" => "invoices#list", as: :invoices_list
  get "/invoices/users/:id" => "invoices#users_list", as: :invoices_users

  resources :cafe
  resources :menu_items
  resources :menu
  resources :order
  resources :users
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>The Cafe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if @current_user %>
      <section class = "CurrentUserBar">
        <p class = "Username">Hello <%= @current_user.name %>! </p>

        <section class = "Buttons">
          <%= button_to("Home", "/", class: "Home-Button", method: "get") %>

          <% if @current_user.role == "owner" || @current_user.role == "billing clerk"%>
            <% if @current_user.role == "owner"%>
              <section class = "NonUserSection">
                <%= button_to("Users", "/users", method: "get", class: "Users-Button") %>
                <%= button_to("Invoices", "/invoices", method: "get", class: "Invoices-Button") %>
              </section>
            <% end %>
            <section class = "NonUserSection">
              <%= button_to("Pending Orders", "/order", method: "get", class: "PendingOrder-Button") %>
            </section>
          <% end %>

          <% if @current_user.role == "customer"%>
            <section class = "UserSection">
              <%= button_to("My Orders", "/order", method: "get", class: "MyOrders-Button") %>
            </section>
          <% end %>

          <%= button_to("Sign-out", destroy_session_path, class: "Signout-Button", method: "delete") %>
        </section>
      </section>
    <% end %>

    <h1 class = "CafePageTitle"> The Cafe..!! </h1>

    <%= yield %>

  </body>
</html>